name: First Workflow
on: 
    push:
        branches:
           - master

jobs:
    greetings:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting step"
              run: echo "This is my first workflow"

            - name: "List the files"
              run: ls -a

            - name: "Complete greeting the user"
              run: echo "Good evening"

