name: "Welcome the User"
on: 
    push:
        branches: 
            - master
jobs: 
    welcome:
        runs-on: ubuntu-latest
        steps:
            - name: "Create tester1 directory"
              run: |
                 mkdir tester123
                 cd tester123
                 touch image.png

            - name: "Uses actions to upload the tester1 directory"
              uses: actions/upload-artifact@v4
              with: 
                name: result
                path: tester123
             
                 
